CREATE TABLE SDB.APP_SEQUENCE
(ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) NOT NULL,
PCYYYY VARCHAR(15) NOT NULL, 
SEQUENCE_NUMBER INTEGER,	
CREATED TIMESTAMP NOT NULL ,  
PRIMARY KEY (ID),
UNIQUE (PCYYYY));

ffffffffff
