CREATE DATABASE IF NOT EXISTS AUDITDB;
USE AUDITDB;

CREATE TABLE IF NOT EXISTS SDBLOS.AUDITLOGS (
    LOGID INT AUTO_INCREMENT PRIMARY KEY,
    SOLUTIONPREFIX VARCHAR(100) NOT NULL,
    REFERENCEID INT NOT NULL,
    ACTIONSTATUS VARCHAR(100) NOT NULL,
    ACTION TEXT NOT NULL,
    ACTIONBYUSERID VARCHAR(255) NOT NULL,
    ACTIONDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
);
