CREATE DATABASE IF NOT EXISTS MASLOSDB;
USE MASLOSDB;


CREATE TABLE SDBLOS.APP_SEQUENCE
(ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) NOT NULL,
PCYYYY VARCHAR(15) NOT NULL, 
SEQUENCE_NUMBER INTEGER,	
CREATED TIMESTAMP NOT NULL ,  
PRIMARY KEY (ID),
UNIQUE (PCYYYY));



CREATE PROCEDURE SDBLOS.GET_SEQUENCE_NUMBER
	(IN pcyear VARCHAR(15),OUT out_seq_num INTEGER)
	LANGUAGE SQL
	MODIFIES SQL DATA

	P1: BEGIN 

	DECLARE count1  INTEGER; 
	DECLARE var_seq_num INTEGER; 
	DECLARE var_pcyyyy VARCHAR(15);
	
	LOCK TABLE SDBLOS.APP_SEQUENCE IN EXCLUSIVE MODE;
 	SELECT COUNT(*) INTO count1 from SDBLOS.APP_SEQUENCE where PCYYYY = pcyear;
  
	IF(count1 <> 0) Then
		
		SELECT PCYYYY INTO var_pcyyyy FROM SDBLOS.APP_SEQUENCE where PCYYYY = pcyear;
		IF(var_pcyyyy = pcyear) Then
		SELECT SEQUENCE_NUMBER+1 INTO var_seq_num FROM SDBLOS.APP_SEQUENCE where PCYYYY = pcyear;
		update SDBLOS.APP_SEQUENCE set SEQUENCE_NUMBER = var_seq_num where PCYYYY = pcyear;

		ELSE
		set var_seq_num = 1;
		update SDBLOS.APP_SEQUENCE set SEQUENCE_NUMBER = var_seq_num  where PCYYYY = pcyear;

		END IF;
		 
	ELSE
	set var_seq_num = 1;
	insert into SDBLOS.APP_SEQUENCE(PCYYYY, SEQUENCE_NUMBER, CREATED) values(pcyear, var_seq_num, CURRENT TIMESTAMP);     

	END IF;
	commit;
set out_seq_num = var_seq_num;
END P1
