CREATE DATABASE IF NOT EXISTS PWNLOSDB;
USE PWNLOSDB;

CREATE TABLE SDBLOS.CASEDETAILS (
    REFERENCEID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCENO VARCHAR(255) NOT NULL,
    STEPNAME VARCHAR(255) NOT NULL,
    BRANCHNAME VARCHAR(255) NOT NULL,
    BRNACHCODE VARCHAR(100) NOT NULL,
    INITIATORUSERID VARCHAR(255) NOT NULL,
    INITIATORUSERNAME VARCHAR(255) NOT NULL,
    MANAGERUSERID VARCHAR(255) NOT NULL,
    MANAGERUSERNAME VARCHAR(255) NOT NULL,
    CASEPRODUCT VARCHAR(255) NOT NULL,
    SOURCE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (REFERENCEID)
);


CREATE TABLE SDBLOS.LOANELIGIBILITY (
    ELIGIBILITYID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    LOANAPPLICATIONRECEIVEDDATE TIMESTAMP NOT NULL,
    APPLICATIONNUMBER VARCHAR(255) NOT NULL,
    APPLICATIONTYPE VARCHAR(255) NOT NULL,
    PRODUCTYPE VARCHAR(255) NOT NULL,
    PRODUCTSUBTYPE VARCHAR(255) NOT NULL,
    TENUREMONTHS INT NOT NULL,
    RELATIONSHIPWITHBANK VARCHAR(255) NOT NULL,
    RELATIONSHIPWITHBANKSTAFFCODE VARCHAR(100),
    NOTETYPE VARCHAR(100),
    LOANTYPE VARCHAR(100),

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (ELIGIBILITYID),
    FOREIGN KEY (REFERENCEID) REFERENCES SDBLOS.CASEDETAILS (REFERENCEID)
);

CREATE TABLE SDBLOS.COREDATADETAILS (
    COREDATADETAILSID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    CAMPAIGN VARCHAR(255),
    CAMPAIGNDICOUNTPERCENTAGE DECIMAL(5,2),
    LOANREQUESTEDAMOUNT DECIMAL(15,2) NOT NULL,
    MATURITYDATE TIMESTAMP NOT NULL,
    TOTALNUMBEROFARTICLES INT,
    TOTALNUMBEROFGROUPS INT,
    TOTALGOLDWEIGHT DECIMAL(10,2),
    LOANPERMISSIBLEAMOUNT DECIMAL(15,2),
    LIMITRECOMMENDEDBYBANKAMOUNT DECIMAL(15,2),
    OUTSTANDINGLOANAMOUNT DECIMAL(15,2),

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (COREDATADETAILSID),
    FOREIGN KEY (REFERENCEID) REFERENCES SDBLOS.CASEDETAILS (REFERENCEID)
);


CREATE TABLE SDBLOS.CUSTOMERDETAILS (
    CUSTOMERID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    CIFNUMBER VARCHAR(100) NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    NICNUMBER VARCHAR(100) NOT NULL,
    PASSPORTNUMBER VARCHAR(100),
    CUSTOMERSINCEDATE TIMESTAMP NOT NULL,
    CORESERVERTYPE VARCHAR(100) NOT NULL,
    CUSTOMERCLASSIFICATION VARCHAR(100) NOT NULL,
    CUSTOMERRELATIONSHIP VARCHAR(5) NOT NULL,
    DOB DATE NOT NULL,
    GENDER VARCHAR(50) NOT NULL,
    CONTACTNUMBER VARCHAR(100) NOT NULL,
    NATIONALITY VARCHAR(100) NOT NULL,
    FACTACAMPILANT VARCHAR(3) NOT NULL,
    COUNTRYNAME VARCHAR(100) NOT NULL,
    SBACCOUNTNUMBER VARCHAR(100),
    IMDACCOUNTNUMBER VARCHAR(100),

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (CUSTOMERID),
    FOREIGN KEY (REFERENCEID) REFERENCES SDBLOS.CASEDETAILS (REFERENCEID)
);


CREATE TABLE SDBLOS.ADDRESSDETAILS (
    ADDRESSID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    CUSTOMERID INT NOT NULL,
    ADDRESSTYPE VARCHAR(100) NOT NULL,
    ADDRESSPROOFSUBMITTED VARCHAR(100),
    ADDRESS CLOB NOT NULL,
    NEARESTLANDBANK VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    POSTALCODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL,
    PHONENUMBER01 VARCHAR(100),
    PHONENUMBER02 VARCHAR(100),
    LANDLINE VARCHAR(100),
    EMAILID VARCHAR(255),

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (ADDRESSID),
    FOREIGN KEY (REFERENCEID) REFERENCES SDBLOS.CASEDETAILS (REFERENCEID),
    FOREIGN KEY (CUSTOMERID)  REFERENCES SDBLOS.CUSTOMERDETAILS (CUSTOMERID)
);

CREATE TABLE SDBLOS.BLACKLISTDATA (
    BLACKLISTID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    SEARCHPARAMETERS CLOB NOT NULL,
    SEARCHRESULTS CLOB NOT NULL,

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (BLACKLISTID),
    FOREIGN KEY (REFERENCEID)  REFERENCES SDBLOS.CASEDETAILS (REFERENCEID)
);


CREATE TABLE SDBLOS.RELATEDPARTIES (
    PARTYID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    REFERENCEID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NICNUMBER VARCHAR(100) NOT NULL,
    ADDRESS01 VARCHAR(255),
    ADDRESS02 VARCHAR(255),
    REMARKS01 CLOB,
    REMARKS02 CLOB,
    RELATEDPARTYASPERSEARCHRESULT VARCHAR(255),
    CONFIRMRELATEDPARTY VARCHAR(3),
    REMARKS CLOB,

    CREATEDATETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,

    PRIMARY KEY (PARTYID),
    FOREIGN KEY (REFERENCEID) REFERENCES SDBLOS.CASEDETAILS (REFERENCEID)
);





