CREATE DATABASE IF NOT EXISTS PWNLOSDB;
USE PWNLOSDB;

CREATE TABLE IF NOT EXISTS SDBLOS.CASEDETAILS (
    REFERENCEID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCENO VARCHAR(255) NOT NULL,
    STEPNAME VARCHAR(255) NOT NULL,
    BRANCHNAME VARCHAR(255) NOT NULL,
    BRNACHCODE VARCHAR(100) NOT NULL,
    INITIATORUSERID VARCHAR(255) NOT NULL,
    INITIATORUSERNAME VARCHAR(255) NOT NULL,
    MANAGERUSERID VARCHAR(255) NOT NULL,
    MANAGERUSERNAME VARCHAR(255) NOT NULL,
    CASEPRODUCT VARCHAR(255) NOT NULL,
    SOURCE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SDBLOS.LOANELIGIBILITY (
    ELIGIBILITYID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    LOANAPPLICATIONRECEIVEDDATE DATETIME NOT NULL,
    APPLICATIONNUMBER VARCHAR(255) NOT NULL,
    APPLICATIONTYPE VARCHAR(255) NOT NULL,
    PRODUCTYPE VARCHAR(255) NOT NULL,
    PRODUCTSUBTYPE VARCHAR(255) NOT NULL,
    TENUREMONTHS INT NOT NULL,
    RELATIONSHIPWITHBANK VARCHAR(255) NOT NULL,
    RELATIONSHIPWITHBANKSTAFFCODE VARCHAR(100),
    NOTETYPE VARCHAR(100),
    LOANTYPE VARCHAR(100),
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
);

CREATE TABLE IF NOT EXISTS SDBLOS.COREDATADETAILS (
    COREDATADETAILSID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    CAMPAIGN VARCHAR(255),
    CAMPAIGNDICOUNTPERCENTAGE DECIMAL(5,2),
    LOANREQUESTEDAMOUNT DECIMAL(15,2) NOT NULL,
    MATURITYDATE DATETIME NOT NULL,
    TOTALNUMBEROFARTICLES INT,
    TOTALNUMBEROFGROUPS INT,
    TOTALGOLDWEIGHT DECIMAL(10,2),
    LOANPERMISSIBLEAMOUNT DECIMAL(15,2),
    LIMITRECOMMENDEDBYBANKAMOUNT DECIMAL(15,2),
    OUTSTANDINGLOANAMOUNT DECIMAL(15,2),
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
);

CREATE TABLE IF NOT EXISTS SDBLOS.CUSTOMERDETAILS (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    CIFNUMBER VARCHAR(100) NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    NICNUMBER VARCHAR(100) NOT NULL,
    PASSPORTNUMBER VARCHAR(100),
    CUSTOMERSINCEDATE DATETIME NOT NULL,
    CORESERVERTYPE VARCHAR(100) NOT NULL,
    CUSTOMERCLASSIFICATION VARCHAR(100) NOT NULL,
    CUSTOMERRELATIONSHIP VARCHAR(5) NOT NULL,
    DOB DATE NOT NULL,
    GENDER VARCHAR(50) NOT NULL,
    CONTACTNUMBER VARCHAR(100) NOT NULL,
    NATIONALITY VARCHAR(100) NOT NULL,
    FACTACAMPILANT VARCHAR(3) NOT NULL,
    COUNTRYNAME VARCHAR(100) NOT NULL,
    SBACCOUNTNUMBER VARCHAR(100),
    IMDACCOUNTNUMBER VARCHAR(100),
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
)

CREATE TABLE IF NOT EXISTS SDBLOS.ADDRESSDETAILS (
    ADDRESSID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    CUSTOMERID INT NOT NULL,
    ADDRESSTYPE VARCHAR(100) NOT NULL,
    ADDRESSPROOFSUBMITTED VARCHAR(100),
    ADDRESS TEXT NOT NULL,
    NEARESTLANDBANK VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    POSTALCODE VARCHAR(20),
    COUNTRY VARCHAR(100) NOT NULL,
    PHONENUMBER01 VARCHAR(100),
    PHONENUMBER02 VARCHAR(100),
    LANDLINE VARCHAR(100),
    EMAILID VARCHAR(255),
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDETAILS(CUSTOMERID)
);

CREATE TABLE IF NOT EXISTS SDBLOS.BLACKLISTDATA (
    BLACKLISTID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    SEARCHPARAMETERS TEXT NOT NULL,
    SEARCHRESULTS TEXT NOT NULL,
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
);

CREATE TABLE IF NOT EXISTS SDBLOS.RELATEDPARTIES (
    PARTYID INT AUTO_INCREMENT PRIMARY KEY,
    REFERENCEID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NICNUMBER VARCHAR(100) NOT NULL,
    ADDRESS01 VARCHAR(255),
    ADDRESS02 VARCHAR(255),
    REMARKS01 TEXT,
    REMARKS02 TEXT,
    RELATEDPARTYASPERSEARCHRESULT VARCHAR(255),
    CONFIRMRELATEDPARTY VARCHAR(3),
    REMARKS TEXT,
    CREATEDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REFERENCEID) REFERENCES CASEDETAILS(REFERENCEID)
);


